### PR TITLE
Initial Attempt At Appveyor

### LINKED ISSUE #8: Add cross-platform tests of CI

### PR DESCRIPTION
**Pull request by arnavb**
Fixes #8

### CODE REVIEW

**Comment by arnavb** [comment]
@iattempt Appveyor is not recognizing this repository, even though I have enabled it. The commit below was pushed from my local environment. Do you have to enable it as well? Also, I need your help in implementing some of the commands in `scripts/test.sh` because I am unsure about their Windows equivalents.

**Review by soc221b — COMMENTED** [review]
Test

**Comment by soc221b** [comment]
Ok, The web-hook is working.

**Comment by soc221b** [comment]
I'll add more info for bash scripts tomorrow.

**Comment by arnavb** [comment]
@iattempt I still can't see the Appveyor build, and I can't verify the problems otherwise.

**Review by soc221b — COMMENTED** [review]
test

**Review by soc221b — COMMENTED** [review]
test

**Comment by iattempt** [comment]
trigger test.

**Comment by soc221b** [comment]
@arnavb Could you push a test commit? It works on #22

**Comment by arnavb** [comment]
/cc @iattempt I am getting an error: `ImportError: No module named 'namanager.tests'` Could you review the appveyor.yml? 

On a side note, I haven't touched .travis.yml and that is failing as well for some reason...

**Comment by soc221b** [comment]
@arnavb 
I think the two errors could be fixed by merge master into this.
Some older commits have problems which have fixed.

**Comment by arnavb** [comment]
(Just did a rebase)

**Comment by arnavb** [comment]
@iattempt Do you have any idea why I'm getting the error:

```
ERROR: Failure: ImportError (No module named 'namanager.tests')
```

3/5 tests are passing on the build.

**Comment by soc221b** [comment]
@arnavb missing move tests into namanager/.  col:139 [test.sh](https://github.com/iattempt/namanager/blob/1b520fca31973510d2d6126b7fa8008b626901a5/scripts/test.sh)

**Comment by soc221b** [comment]
@arnavb Do you know why can't I access project by specified branch?
https://ci.appveyor.com/project/iattempt/namanager/branch/master

[This works...](https://github.com/uncrustify/uncrustify/blob/master/README.md)

**Comment by arnavb** [comment]
@iattempt Actually, I have no clue. Looks like something might have happened with how Appveyor handles the shield's service. If you remove the branch, then it works fine. I would still stick with the official badge for now. You could also contact Appveyor at help.appveyor.com (I have done it before, and they are very helpful) On the other hand, you could open an issue at shields.io! 😉 

Example:

Default:
Appveyor

Master branch:
Appveyor

**Comment by soc221b** [comment]
@arnavb Do you working on batch script for windows?

**Comment by arnavb** [comment]
@iattempt You may be wondering why I was AFC for the complete length of the last week. Well, it turns out, I was on vacation, so I had no access to a computer (Or internet for that matter). I will get back to all my Github activity tomorrow! 😁

**Comment by arnavb** [comment]
Closing for now, as this PR has been jumbled beyond recognition; will try sometime in the future.

**Pull request closed without merging**
