### PR TITLE
Tell codecov to ignore our test folder

### PR DESCRIPTION
**Pull request by arnavb**

### CODE REVIEW

**Comment by arnavb** [comment]
Well, apparently Codecov cares a lot about our test file. Any ideas as to what I should do @iattempt?

**Comment by soc221b** [comment]
I think we shouldn't ignore those warnings, we could change strategy for testing.
e.g.,:
```python
if some error occurs:
    append_error_msg("something not passed")  # this will be not covered

if some other error occurs:
    append_error_msg("something not passed")  # this will be not covered also
```

could be changed as (but this isn't a good implement and demo also):
```python
def check_and_append(predicate, msg):
    if some error occurs:
        append_error_msg("something not passed")   # only this will be not covered

check_and_append_msg(predicate, "something not passed.")  # this will be covered
check_and_append_msg(predicate, "something else not passed.")  # also, this will be covered
```

**Comment by arnavb** [comment]
@iattempt It isn't clear to me how this relates to just not getting the coverage of our test files, since we _don't_ have coverage for our test files. It doesn't make sense to check how many lines of our tests are run, since they are tests. It only matters how many lines the tests run themselves.

**Comment by soc221b** [comment]
@arnavb In some cases else, developer may write _unnecessary_ code in test files, it will be hard to found and maintained. Thus, I think that those warning should be included, and also minimize using the ignore lines (`# pragma: no cover`).

**Comment by arnavb** [comment]
Ok, so instead of excluding the file, where should I exclude coverage? (Which branches should be included, and which shouldn't?)

Comment:
```Python
# pragma: no cover
```

**Comment by soc221b** [comment]
IMHO, we just need fewer functions like [this](https://github.com/iattempt/FileChecker/blob/backup/src/main.py):

screen shot 2018-03-12 at 11 27 48 pm

**Comment by arnavb** [comment]
I'll open another PR.

**Pull request closed without merging**
